name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a bug report.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug you experienced in a conscise manner.
      placeholder: Tell us what happened in a conscise manner.
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Describe how to consistently reproduce the bug, if you know.
      placeholder: Enter here.
    validations:
      required: true
    id: actual-behaviour
    attributes:
      label: Actual Behaviour
      description: Describe what you actually happened.
      placeholder: Tell us what actually happened (screenshots are welcome).
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Is there any additional information that may be useful in solving the bug?
      placeholder: Tell us any additional information.
    validations:
      required: true
